[package]
name = "ecg-common"
version = "0.0.0"
edition = "2021"

[features]
tracy = ["tracy-client"]

[dependencies]
glam.workspace = true
spin_sleep = "1.1"
tracing = { version = "0.1", default-features = false }

tracy-client = { version = "0.15.0", optional = true }
